### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by RowenStipe** [Satoqz/command.ts#100]
When attempting to [compile](https://travis-ci.com/github/Charisma-Bonus/vscode-discord.js-typescript-bootstrap/jobs/450272531#L239) `tsc` errors.

I've been able to solve this locally by editing [Client.ts](Satoqz/command.ts/blob/master/src/Client.ts) to import discord.js as
```TS
import { Message } from "discord.js";
import * as discordjs from"discord.js";
```

**Comment by Satoqz** [comment]
Will take a look at this later. I'm guessing though that it might be an issue with your tsconfig

**Comment by Satoqz** [comment]
Alright so, after taking a closer look at the travis log, you can notice that while tsc should only build your own source files, it also tries to transpile the command.ts source files which are only included in the npm release package for typings and easy reference. Those files shouldn't be retranspiled by you, instead the finished js files are obviously provided in the package. To resolve your issue, you'll simply have to exclude the `node_modules` fodler in your `tsconfig.json` as so:
```json
{
  "exclude": [
    "./node_modules"
  ]
}
```
Please report back whether this fixes your problem or not :)

**Comment by RowenStipe** [comment]
Apologies for a late response.

I've tried different ways to exclude the `node_modules` folder.
```json
{
  "exclude": ["./node_modules","node_modules","node_modules/**/*"]
}
```
But it errors out all the same, even on my local machine after reverting my own changes mentioned above. Doing a bit of reading the `"exclude":[] ` property by default excludes `node_modules` https://www.typescriptlang.org/tsconfig#exclude .

The following is my current `tsconfig.json` file for inspection of any glaring issue I might be overlooking.
```json
{
  "include": ["src/**/*"],
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "outDir": "build",
    "experimentalDecorators": true,
    "sourceMap": true,
    "resolveJsonModule": true
  }
}
```

**Comment by RowenStipe** [comment]
So after doing some experimentation on my own. I've discovered that I need to include `"esModuleInterop": true` into my tsconfig. You where correct about it being an issue with my tsconfig file.

Would recomend including this into troubleshooting docs.

Closing issue.
